### ISSUE TITLE
Relations

### ISSUE THREAD

**Issue by Wemago** [xeoncross/1kb-PHP-MVC-Framework#4] opened 2014-04-23 23:25 UTC
I've been playing again with this system which I really enjoy.
Now there's one thing, I've got three tables 

```
Users: user_id
```

```
Groups: group_id
```

```
Groups_Users: id, group_id, user_id
```

I'm trying to get user information using this relation.

```
$groups = new Groups();
foreach($groups->get() as $group):
    echo $group->user->name;
endforeach();
```

The results I get its the information from Groups_Users but not from Users. How would you do this? ( I don't know if this makes any sense to you )

**Comment by xeoncross** [comment] 2014-04-26 18:49
I'm not sure off the top of my head, but you might have to call the other table as a relation.

```
$groups = new Groups();
foreach($groups->get() as $group):
    echo $group->user()->name;
endforeach();
```

**Comment by Wemago** [comment] 2014-04-27 18:46
I've tried that but it doesn't work either.
From what I get it looks like that it only calls/loads at level 1 if you have more levels it doesn't work or I'm wrong and not seeing the picture correctly?

**Comment by xeoncross** [comment] 2014-04-28 02:38
Have you done it one at a time?

```
$group->groups_users->get()
foreach($groups_user....
    $group_user->user->name;
```

**Comment by Wemago** [comment] 2014-05-08 22:08
It doesn't work either. It would be nice to have a solution for this just like you have in your micro database class

**Comment by xeoncross** [comment] 2014-05-09 02:47
Just updated the system with a sample of how to use the ORM and define the relations. It's been quite a while since I built this system and it needs some updating.

**Comment by Wemago** [comment] 2014-05-13 10:49
I'm trying to fix this. I think that the problem is at orm::__call, here:

```
$a[0][$t::$f] = $t->{$t::$k};
```

Try this and you'll get this result.

```
foreach($users->get() as $user) {
    foreach($user->groups() as $groups) {
        foreach($groups->group() as $group) {
            print_r($group);
        }
    }
}
```

```
    [1] => SELECT * FROM `user`
    [2] => SELECT * FROM `group_user` WHERE `user_id`=?
    [3] => SELECT * FROM `group` WHERE ``=?
```

Something like this should work and it gets there but the where clause breaks because the condition isn't filled in.

Doing a if clause replacing $t::$f by $t::$k almost fixes this problem but it only gets the info for the first foreach and produces 3 extra query's without the need of it.

Or we could set in group_user model something like

```
    static $r = array(
        'user' => array( 'class' => 'model_user', 'fk' => 'user_id'),
        'group' => array('class' => 'model_group', 'fk' => 'group_id')
    );

```

**Comment by Wemago** [comment] 2014-05-13 21:51
With few changes I've managed to do this

```
$groups = new Group();
foreach( $groups->get() as $group ) {
    print '<p>';
    print "<b>{$group->group} ({$group->id}):</b><br />";
    foreach( $group->members() as $members ) {
        foreach( $members->user->get( array( 'id' => $members->user_id ) ) as $user ) {
            print "{$user->name} ({$user->id})<br />";
        }
    }
    print '</p>';
}
```

It works has supposed but I'm still not happy with it. It should be possible to do

```
$members->user()
```

and not

```
$members->user->get()
```

I've noticed that "belongs" its not called as a method but only as a key in __get and it only worked after changing somethings.

Now my models look like this

```
class User extends ORM {

    static $t = 'user';

    static $r = array(
        'groups' => array( 'c' => 'GroupUser', 'fk' => 'user_id' )
    );
}
```

```
class Group extends ORM {

    static $t = 'group';

    static $r = array(
        'members' => array( 'c' => 'GroupUser', 'fk' => 'group_id' )
    );
}
```

```
class GroupUser extends ORM {

    static $t = 'group_user';

    static $b = array(
        'user' => array( 'c' => 'User', 'fk' => 'user_id' ),
        'group' => array( 'c' => 'Group', 'fk' => 'group_id' )
    );
}
```

Here are the changes

```
    function __get($k) {

        $t = $this;
        $t->load();

        return ($m = v($t::$r[$k]['c'])) ? current($t->$k(array(), 1)) : (($m = v($t::$b[$k]['c'])) ? new $m(v($t->d[$m::$f])) : parent::__get($k));
    }
```

and

```
    function __call($m, $a) {

        $t = $this;

        $a = $a+array(1 => 0, 0, 0);

        $a[0][$t::$r[$m]['fk']] = $t->{$t::$k};

        $m = new $t::$r[$m]['c'];

        return $m->get($a[0], $a[1], $a[2], $a[3]);
    }
```

**Comment by xeoncross** [comment] 2014-05-13 22:37
Good changes, I'm reopening the issue so that these might be merged back in, the problem is fitting all this in only 1kB which is why it was lacking some features to begin with.

**Comment by Wemago** [comment] 2014-05-13 23:29
It still fits the goal of 1kb :)
The changes I'm making it's with that goal always in mind.

Next step its to fix where clause to add OR or to make it more flexible.
I think that this line can be replaced

```
return $m->get($a[0], $a[1], $a[2], $a[3]);
```

by something like this

```
return $m->get($a['w'], $a['l'], $a['o'], $a['s']);
```

where $a['w'] would be something like

```
array('w' => array('name = ? OR date >= now', array( 'name' => $name)));
```

This allows us to set our preferences for query in the controller/model and making the db/orm class lighter. I'm missing JOIN clauses too, lets see what can I do. With the above example we have 9 queries and with joins I think we can reduce it to 4 or 5 queries only.

I still think that "belongs" relation should be added to the __call method so we can do something like this

```
foreach($members->user( array( 'id' => $members->user_id ) ) as $user) {
    print_r($user);
}
```

**Comment by Wemago** [comment] 2014-05-14 16:28
I've managed to make ORM::__call to work with "belongs" relations, its not that pretty and I think we can reduce the size of the method.

Now we can do this

```
$groups = new Group();
foreach( $groups->get() as $group ) {
    print '<p>';
    print "<b>{$group->group} ({$group->id}):</b><br />";
    foreach( $group->members() as $members ) {
        foreach( $members->user( array( 'id' => $members->user_id ) ) as $user ) {
            print "{$user->name} ({$user->id})<br />";
        }
    }
    print '</p>';
}
```

This are the changes for ORM::__call

```
    function __call($m, $a) {

        $t = $this;

        $a = $a+array(1 => 0, 0, 0);

        if( v( $t::$r[$m]['c'] ) ) {
            $a[0][$t::$r[$m]['fk']] = $t->{$t::$k};
            $c = new $t::$r[$m]['c'];
        } elseif( v( $t::$b[$m]['c'] ) ) {
            $c = new $t::$b[$m]['c'];
            $a[0][$c::$k] = $t->{$t::$b[$m]['fk']};
        }

        return $c->get($a[0], $a[1], $a[2], $a[3]);
    }
```

Now there's one problem, I've got 5 tables and with the system like this it makes 27 queries to the DB and just a small group of data is inserted...If you have 1000 requests / second and thousands of rows the system will be really slow...We're talking about thousands of requests per second...

I think we can fix this with JOIN.

**Comment by Wemago** [comment] 2014-05-15 07:57
With this modifications ORM::count() doesn't work as supposed. It doesn't do relations counting.

**Closed as completed** 2020-11-13 21:51 UTC
